name: Build and Push

on:
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"

# permissions are needed if pushing to ghcr.io
permissions: 
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: homedash-meta
        uses: docker/metadata-action@v4
        with:
          images: |
            name=ghcr.io/mvdkleijn/homedash,enable=true
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
            context: .
            push: true
            platforms: "linux/amd64,linux/arm64"
            tags: ${{ steps.homedash-meta.outputs.tags }}
            labels: ${{ steps.homedash-meta.outputs.labels }}
    