name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Build for Linux amd64
        run: GOOS=linux GOARCH=amd64 go build -v -ldflags="-w -s" -o homedash-linux-amd64 .

      - name: Build for Linux arm64
        run: GOOS=linux GOARCH=arm64 go build -v -ldflags="-w -s" -o homedash-linux-arm64 .

      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@348e88fab4c37338b1e803ceb2d4a7a5db6c0833 # v6.2.2

      - name: Release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          files: ./homedash-*
          generate_release_notes: true
          append_body: true
          body: "${{steps.build_changelog.outputs.changelog}}"
