name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Install dependencies
        run: go get .

      - name: Build for Linux amd64
        run: GOOS=linux GOARCH=amd64 go build -v -ldflags="-w -s" -o homedash-linux-amd64 .

      - name: Build for Linux arm64
        run: GOOS=linux GOARCH=arm64 go build -v -ldflags="-w -s" -o homedash-linux-arm64 .

      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v4.1.1

      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: ./homedash-*
          generate_release_notes: true
          append_body: true
          body: "${{steps.build_changelog.outputs.changelog}}"
